<?php
   if ($_REQUEST['hits'] == "-1") return;
    $arr_hits = explode("-", $p['hits']);
    //$arr_hits[13]  // Value of AppPaid True if its more than zero
    //$arr_hits[12] // Value of Try to open buy now dialog
    
	$q =  "SELECT * FROM `tbl_shifa_log` where Name = 'Counter~Home~Remove~ads~Paid' and session_id = '".$p['session_id']."'"; 
    $res = mysql_query($q);
    $num_rows = mysql_num_rows($res);
    
    if (!$num_rows)
    {
		$q =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
			VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Remove~ads~Paid',  1,NOW(),NOW());";
		$res = mysql_query($q);		
    }
	else{
   
		$q =  "SELECT * FROM `tbl_shifa_log` where Name = 'Counter~Home~Remove~ads~Paid' and session_id = '".$p['session_id']."' and data != 0"; 
		$res = mysql_query($q);
		$num_rows = mysql_num_rows($res);
		$paid = false;
		if ($num_rows)
		{
			$paid = true;
		}
		if ($paid == false) // so paid is false
		{
    // Sending Payment Notification Email
    if ($arr_hits[12] != "" && $arr_hits[12] != "0" )
    {
        //Send Email
        $q =  "SELECT fname, password,email FROM `tbl_app_registration` WHERE session_id = '".$_REQUEST['session_id']."'"; 
     
        $res = mysql_query($q);
        $num_rows = mysql_num_rows($res);
        if ($num_rows)
        {
                $row = mysql_fetch_array($res);
                $password = $row['password'];
                $fname = $row['fname'];
                $EmailFrom = "shifa-buynow@shifa.us";
                $EmailTo = $row['email'];
                $Subject = "WebPayment Call From Shifa, Are you unable to make Payment?";

                // prepare email body text
          $Body = "Dear ".$fname.", 
\r\n\r\nThank you for using Shifa App and giving such good response. We are working very hard to make Homeopathy in hand. We are working to include many books in different language translations for Germary, Italy, Spanish, Brazil, Portugal, France and Dutch users. \r\n\r\nA little background about Shifa team; we don't have a big team or company for financing Shifa Team. Developer(Nasir Sayed) and Doctor(Nazim Dadan) are giving personal time for making Shifa App for all of doctors like you to save money from buying big expensive software. Our vision is to create electronic books (database) with all Homeopathy book one by one. We are spending our own money to maintain infrastructure such as Database, Third Party Server, Source Code, Registration, Android bug fixes from user requests. Doctor: Nazim Dadan and Developer: Nasir Sayed have paid a lot to maintain Shifa service for the past three years and will continue to do it until we don't achieve it for iOS, WebSite & PC Software. \r\n\r\nWe want you to contribute more money for Shifa App account so that we can provide you with more desired features. \r\n\r\nIf you find any difficulties in payment with Google credit card processing or Google is not accepting your payment due to bad card or debit card issue. You can try to make payment online through WebPayment/Paypal Now!\r\n\r\nShifa account is also associated with PayPal payment processing. PayPal accept debit card, credit card or your existing PayPal Account. Its 100% safe money transfer for payment. If you ever find any problem in PayPal transfer then please do not hesitate to ask question to the developer at nasihere@gmail.com\r\n\r\nYou can also follow below URL for payment online NOW!
http://kent.nasz.us/app_php/buynow/buynowwebpayment.php?session_id=".$_REQUEST['session_id']."
Please click on this click and contribute Shifa App for Life time development. No hidden Cost, No Additional Fee in future. \r\n\r\nFor Indian resident:\r\nYou can also pay cash/direct deposit to our bank account. Complete Bank details you can find below.\r\nAccount Name: Nasir Sayed \r\nAmount: 180.00Rs.\r\nAccount No:910010020952010\r\nIFSC Code:UTIB0000219\r\nSwift Code: AXISINBB219\r\nBank - Branch:Axis Bank - Goregaon-LinkRoad, Mumbai, India\r\nWhen you are done with direct deposit to bank account, please reply with email subject 'MONEY TRANSFERED' and account details. We will then update your account as paid customer during US business hour between 9AM To 5PM PST.\r\n\r\n\r\nJust incase if you forgot your username or password after logout. \r\nYour Username: ".$EmailTo."\r\nYour Password: ".$password."\r\n\r\nSincerely, \r\nThe Shifa App Team\r\nNasir Sayed\r\n<Note: Its an autogenerated email, Do not reply to this email. if you have any queries please email to nasihere@gmail.com>"; 
                

                // send email 
            //  $success = mail($EmailTo, $Subject, $Body, "From: <$EmailFrom>");
                $success = mail("nasihere@gmail.com", "WebRequest", $fname . " - " . $_REQUEST['session_id'], "From: <shifarequest@shifa.us>");

            
            
        }
    
    }
       
    
    }
    }
    if ($arr_hits[13] != "" && $arr_hits[13] != "0" && $paid == false)
    {
          $success = mail("nasihere@gmail.com", "ShifaPurchased", $fname . " - " . $_REQUEST['session_id'], "From: <shifapurchased@shifa.us>");
    }
    
    
    
    
    $q =  "SELECT session_id FROM `tbl_shifa_log` where session_id = '".$p['session_id']."'"; 
    $res = mysql_query($q);
    $num_rows = mysql_num_rows($res);
    if ($num_rows)
    {
       $q1 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[0]." where Name =  'Counter~Home~Kent-Repertory' and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[1] != "0")
        $q2 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[1]." where Name =  'Counter~Home~Materia-Medica'  and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[2] != "0")
        $q3 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[2]." where Name =  'Counter~Home~Reveresed-Repetory'  and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[3] != "0")
        $q4 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[3]." where Name =  'Counter~Home~Abbreviation'  and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[4] != "0")
        $q5 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[4]." where Name =  'Counter~Home~Chat'  and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[5] != "0")
        $q6 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[5]." where Name =  'Counter~Home~Event'  and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[6] != "0")
        $q7 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[6]." where Name =  'Counter~Home~Flash'  and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[7] != "0")
        $q8 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[7]." where Name =  'Counter~Home~Logout'  and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[8] != "0")
        $q9 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = ".$arr_hits[8]." where Name =  'Counter~Home~ChatIndex'  and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[9] != "0")
         $q10 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[9]." where Name =  'Counter~Home-Organon'  and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[10] != "0")
        $q11 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[10]." where Name =  'Counter~Home-Menu'  and session_id = '" . $p['session_id'] . "'";
      if ($arr_hits[11] != "0")  
        $q12 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[11]." where Name =  'Counter~Home-URL'  and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[12] != "0")
           $q13 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[12]." where Name =  'Counter~Home~Remove~ads'  and session_id = '" . $p['session_id'] . "'";
        if ($arr_hits[13] != "0")
          $q14 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data =  ".$arr_hits[13]." where Name =  'Counter~Home~Remove~ads~Paid'  and session_id= '" . $p['session_id'] . "'";
        if ($arr_hits[14] != "0")
          $q15 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = Data + ".$arr_hits[14]." where Name =  'Counter~Home~PrivateMsg'  and session_id= '" . $p['session_id'] . "'";
        //01/29/2014 Cancel Paid auto service -
		//05/01/2014 Enabled Paid User
        // $q14 =  "UPDATE `tbl_shifa_log` SET  lastvisitdatetime = NOW(), Data = 1 where Name =  'Counter~Home~Remove~ads~Paid'  and session_id= '" . $p['session_id'] . "'";
        
        
    }
    else
    {
    
  $q1 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime` )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Kent-Repertory',  ".$arr_hits[0].",NOW(),NOW());";
  
  $q2 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Materia-Medica',  ".$arr_hits[1].",NOW(),NOW());";
  
  $q3 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Reveresed-Repetory',  ".$arr_hits[2].",NOW(),NOW());";
  
  $q4 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Abbreviation',  ".$arr_hits[3].",NOW(),NOW());";
  
  $q5 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Chat',  ".$arr_hits[4].",NOW(),NOW());";
  
  $q6 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Event',  ".$arr_hits[5].",NOW(),NOW());";
  
  $q7 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Flash',  ".$arr_hits[6].",NOW(),NOW());";
  
  $q8 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Logout',  ".$arr_hits[7].",NOW(),NOW());";
  
  $q9 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~ChatIndex',  ".$arr_hits[8].",NOW(),NOW());";
        
  $q10 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Organon',  ".$arr_hits[9].",NOW(),NOW());";
        
  $q11 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Menu',  ".$arr_hits[10].",NOW(),NOW());";
        
  $q12 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~URL',  ".$arr_hits[11].",NOW(),NOW());";
  
        $q13 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Remove~ads',  ".$arr_hits[12].",NOW(),NOW());";
        
        //Paid service off = Major change 01/29/2014 Made Shifa payable again
         //$q14 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
//VALUES ( NLL,  '".$p['session_id']."',  'Counter~Home~Remove~ads~Paid',  ".$arr_hits[13].",NOW(),NOW());";
		
		
		//Paid auto service on = 	// major changed 05/01/2015 Changes
        $q14 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~Remove~ads~Paid',  1,NOW(),NOW());";
        
        
         $q15 =  "INSERT INTO  `tbl_shifa_log`  (  `_id` ,  `session_id` ,  `Name` ,  `Data`, `datetime`, `lastvisitdatetime`  )
VALUES ( NULL,  '".$p['session_id']."',  'Counter~Home~PrivateMsg',  ".$arr_hits[14].",NOW(),NOW());";
        
         }
    
            if ($q1 != "")    $result =  mysql_query($q1);
     
            if ($q2 != "")    $result =  mysql_query($q2);
         if ($q3 != "")       $result =  mysql_query($q3);
         if ($q4 != "")    $result =  mysql_query($q4);
            if ($q5 != "") $result =  mysql_query($q5);
            if ($q6 != "") $result =  mysql_query($q6);
            if ($q7 != "") $result =  mysql_query($q7);
            if ($q8 != "") $result =  mysql_query($q8);
            if ($q9 != "") $result =  mysql_query($q9);
            if ($q10 != "") $result =  mysql_query($q10);
    
         if ($q11 != "")    $result =  mysql_query($q11);
         if ($q12 != "")    $result =  mysql_query($q12);
         if ($q13 != "") $result =  mysql_query($q13);
      if ($q14 != "")  $result =  mysql_query($q14);
             if ($q15 != "")    $result =  mysql_query($q15);
?>